/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SpringBoot.Proxys;

public class App {
    public static void main(String[] args) {

        Man mohan = new Man("Mohan", 25, "Delhi", "India");

        //reflection is  used to create the proxy object
        ClassLoader mohanClassLoader = mohan.getClass().getClassLoader();
        class[] interfaces = mohan.getClass().getClasses();
        Class[] interfaces = mohan.getClass().getInterfaces();
        Person proxyMohan = Prox
    }
}
