/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SpringBoot.Proxys;

import java.lang.reflect.Proxy;

public class App {
    public static void main(String[] args) {

        Man mohan = new Man("Mohan", 25, "Delhi", "India");

        //reflection is  used to create the proxy object
        ClassLoader mohanClassLoader = mohan.getClass().getClassLoader();
        Class[] interfaces = mohan.getClass().getInterfaces();
        Person proxyMohan = (Person) Proxy.newProxyInstance(mohanClassLoader, interfaces, new PersonInvocationHandler(mohan));
        proxyMohan.introduce("Mohan");

        proxyMohan.sayAge(25);

        proxyMohan.sayNationality("Delhi", "India");


    }
}
